config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :plans

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :plan_items
end

app/models/plan_item.rb
class PlanItem < ActiveRecord::Base
  belongs_to :plan
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:title)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.slim
= form_for @plan do |f|
  - if @plan.errors.any?
    #error_explanation
      h2 = "#{pluralize(@plan.errors.count, "error")} prohibited this plan from being saved:"
      ul
        - @plan.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_area :title
  .actions = f.submit

app/views/plans/edit.html.slim
h1 Editing plan

== render 'form'

=> link_to 'Show', @plan
'|
=< link_to 'Back', plans_path

app/views/plans/index.html.slim
h1 Listing plans

table
  thead
    tr
      th Title
      th
      th
      th

  tbody
    - @plans.each do |plan|
      tr
        td = plan.title
        td = link_to 'Show', plan
        td = link_to 'Edit', edit_plan_path(plan)
        td = link_to 'Destroy', plan, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Plan', new_plan_path

app/views/plans/new.html.slim
h1 New plan

== render 'form'

= link_to 'Back', plans_path

app/views/plans/show.html.slim
p#notice = notice

p
  strong Title:
  = @plan.title

=> link_to 'Edit', edit_plan_path(@plan)
'|
=< link_to 'Back', plans_path